package Demo17_Exception;

public class Test5 {
    //重载：
    public void a()throws Exception{

    }
    public void a(int a)throws Exception{}
}


